server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/USER
    username: root
    password: persona4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Ms User"
appVersion: "1.0.0"
